### ISSUE TITLE
[Oct 9] Allow a grace period before closing a submission phase

### ISSUE THREAD

**Issue by LowPolyCount** [magfest/mivs#99]
IE, If we close at 11:59pm, don't close until 12:09am.  This will help prevent confusion.

**Comment by LowPolyCount** [comment]
If we could get this for phase 2 closing (September 30th, 2017) that would be an incredible help!

**Comment by thaeli** [comment]
..why can't we just set the close time in the system later than we announce
the close time to be?

I understand the intent of this change, but it does add non-intuitive
behavior (making the system behave in a different fashion than the config
file states) and we should avoid that as much as possible.

**Comment by kitsuta** [comment]
The literal answer to your question is that the string that shows the
deadline (e.g., on the application page, in the emails) is the same date
string that's actually used for the deadline.

We can add a buffer... it would be pretty non-standard in comparison to
other deadlines, but it wouldn't be too tricky. Most deadlines in the
system are not fuzzy, though, and I think we'd like to keep it that way.

**Comment by thaeli** [comment]
Ah. I'd prefer to implement as adding new "public_closing_time" config
options instead of a grace period in only this one place.

**Comment by kitsuta** [comment]
I think in some ways having it be unique to the MIVS plugin/workflow makes
business-logic sense. If someone can't manage to fill out a regular ol'
form in time, they're just being silly... but with something like prepping
a game or video for submission, there's like a million things that can go
wrong on you. I imagine it's like when you've finished your essay just in
time for school but then the printer decides that functioning is
optional... except you have four different steps that are that printer
(video editing/exporting software, YouTube/other service upload,
YouTube/other service PROCESSING, probably more I haven't thought of). In
that case, an extra 10 minutes' leeway makes sense, because the submitter
may have that kind of delay introduced by other steps in the submission
process that are outside of their (and our) control.

**Comment by kitsuta** [comment]
Gonna try to get this done before the new round two deadline on Oct 9th!
